# Generated by Django 5.1.5 on 2025-02-04 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donatur', '0001_initial'),
        ('kampanye', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donasi',
            name='kampanye',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kampanye.kampanye'),
        ),
    ]
