# Generated by Django 5.1.5 on 2025-02-04 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kampanye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('target_dana', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dana_terkumpul', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tanggal_mulai', models.DateField(auto_now_add=True)),
                ('tanggal_berakhir', models.DateField()),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='kampanye_images/')),
                ('pengelola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
