# Generated by Django 5.1.5 on 2025-02-04 03:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kampanye', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kampanye',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kampanye',
            name='status',
            field=models.CharField(choices=[('aktif', 'Aktif'), ('selesai', 'Selesai'), ('dibatalkan', 'Dibatalkan')], default='aktif', max_length=10),
        ),
        migrations.AddField(
            model_name='kampanye',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='kampanye',
            name='pengelola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kampanye_dikelola', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kampanye',
            name='tanggal_mulai',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
