# Generated by Django 5.1.5 on 2025-02-04 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kampanye', '0002_kampanye_created_at_kampanye_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PembaruanKampanye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('kampanye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pembaruan_kampanye', to='kampanye.kampanye')),
            ],
        ),
    ]
