# Generated by Django 5.1.5 on 2025-02-04 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kampanye', '0003_pembaruankampanye'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pembaruankampanye',
            name='kampanye',
        ),
        migrations.RemoveField(
            model_name='pembaruankampanye',
            name='tanggal_dibuat',
        ),
    ]
